// =====================================================================
// Dim_Date — paste as a separate Blank Query in Advanced Editor
// Covers 2015-01-01 through 2018-02-01, the real min/max span of
// OrderDate/ShippingDate in the DataCo dataset.
// =====================================================================
let
    StartDate = #date(2015,1,1),
    EndDate   = #date(2018,2,1),
    NumberOfDates = Duration.Days(EndDate - StartDate) + 1,
    DateList = List.Dates(StartDate, NumberOfDates, #duration(1,0,0,0)),
    TableFromList = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}),
    ChangedType = Table.TransformColumnTypes(TableFromList, {{"Date", type date}}),
    AddedDateKey = Table.AddColumn(ChangedType, "DateKey", each Date.ToText([Date], "yyyyMMdd"), type text),
    ChangedKeyType = Table.TransformColumnTypes(AddedDateKey, {{"DateKey", Int64.Type}}),
    AddedDay = Table.AddColumn(ChangedKeyType, "Day", each Date.Day([Date]), Int64.Type),
    AddedMonth = Table.AddColumn(AddedDay, "Month", each Date.Month([Date]), Int64.Type),
    AddedMonthName = Table.AddColumn(AddedMonth, "MonthName", each Date.MonthName([Date]), type text),
    AddedQuarter = Table.AddColumn(AddedMonthName, "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
    AddedYear = Table.AddColumn(AddedQuarter, "Year", each Date.Year([Date]), Int64.Type),
    AddedWeekday = Table.AddColumn(AddedYear, "Weekday", each Date.DayOfWeek([Date],Day.Monday) + 1, Int64.Type),
    AddedWeekdayName = Table.AddColumn(AddedWeekday, "WeekdayName", each Date.DayOfWeekName([Date]), type text),
    AddedIsWeekend = Table.AddColumn(AddedWeekdayName, "IsWeekend", each [Weekday] >= 6, type logical),
    Reordered = Table.ReorderColumns(AddedIsWeekend, {"DateKey","Date","Day","Month","MonthName","Quarter","Year","Weekday","WeekdayName","IsWeekend"})
in
    Reordered
