// =====================================================================
// POWER QUERY M SCRIPT — Base cleaning query
// Paste into: Power BI Desktop → Transform Data → New Blank Query → Advanced Editor
// (Update the file path in Csv.Document to wherever SupplyChain.csv sits on YOUR machine)
// =====================================================================

let
    Source = Csv.Document(
        File.Contents("C:\Path\To\SupplyChain_Visibility_Optimization\Milestone1\data\SupplyChain.csv"),
        [Delimiter=",", Columns=53, Encoding=1252, QuoteStyle=QuoteStyle.None]
    ),
    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),

    // 1. Remove fully-empty / unnecessary columns (Product Description is 100% null; drop PII fields)
    RemovedColumns = Table.RemoveColumns(PromotedHeaders,
        {"Product Description", "Customer Email", "Customer Password", "Customer Fname",
         "Customer Lname", "Customer Street", "Product Image"}),

    // 2. Remove duplicates on the natural grain key
    RemovedDuplicates = Table.Distinct(RemovedColumns, {"Order Item Id"}),

    // 3. Correct data types
    ChangedType = Table.TransformColumnTypes(RemovedDuplicates,{
        {"Type", type text}, {"Days for shipping (real)", Int64.Type},
        {"Days for shipment (scheduled)", Int64.Type}, {"Benefit per order", type number},
        {"Sales per customer", type number}, {"Delivery Status", type text},
        {"Late_delivery_risk", Int64.Type}, {"Category Id", Int64.Type},
        {"Category Name", type text}, {"Customer City", type text},
        {"Customer Country", type text}, {"Customer Id", Int64.Type},
        {"Customer Segment", type text}, {"Customer State", type text},
        {"Customer Zipcode", Int64.Type}, {"Department Id", Int64.Type},
        {"Department Name", type text}, {"Latitude", type number},
        {"Longitude", type number}, {"Market", type text}, {"Order City", type text},
        {"Order Country", type text}, {"Order Customer Id", Int64.Type},
        {"order date (DateOrders)", type datetime}, {"Order Id", Int64.Type},
        {"Order Item Cardprod Id", Int64.Type}, {"Order Item Discount", type number},
        {"Order Item Discount Rate", type number}, {"Order Item Id", Int64.Type},
        {"Order Item Product Price", type number}, {"Order Item Profit Ratio", type number},
        {"Order Item Quantity", Int64.Type}, {"Sales", type number},
        {"Order Item Total", type number}, {"Order Profit Per Order", type number},
        {"Order Region", type text}, {"Order State", type text}, {"Order Status", type text},
        {"Order Zipcode", type number}, {"Product Card Id", Int64.Type},
        {"Product Category Id", Int64.Type}, {"Product Name", type text},
        {"Product Price", type number}, {"Product Status", Int64.Type},
        {"shipping date (DateOrders)", type datetime}, {"Shipping Mode", type text}
    }),

    // 4. Handle remaining nulls (Customer Zipcode: 3 nulls, Order Zipcode: ~155,679 nulls -> 0/Unknown)
    ReplacedCustZip = Table.ReplaceValue(ChangedType, null, 0, Replacer.ReplaceValue, {"Customer Zipcode"}),
    ReplacedOrderZip = Table.ReplaceValue(ReplacedCustZip, null, 0, Replacer.ReplaceValue, {"Order Zipcode"}),

    // 5. Rename columns to meaningful, consistent names
    RenamedColumns = Table.RenameColumns(ReplacedOrderZip,{
        {"Type", "PaymentType"}, {"Days for shipping (real)", "DaysForShippingReal"},
        {"Days for shipment (scheduled)", "DaysForShipmentScheduled"},
        {"Benefit per order", "BenefitPerOrder"}, {"Sales per customer", "SalesPerCustomer"},
        {"Delivery Status", "DeliveryStatus"}, {"Late_delivery_risk", "LateDeliveryRisk"},
        {"Category Id", "CategoryID"}, {"Category Name", "CategoryName"},
        {"Customer City", "CustomerCity"}, {"Customer Country", "CustomerCountry"},
        {"Customer Id", "CustomerID"}, {"Customer Segment", "CustomerSegment"},
        {"Customer State", "CustomerState"}, {"Customer Zipcode", "CustomerZipcode"},
        {"Department Id", "DepartmentID"}, {"Department Name", "DepartmentName"},
        {"Order City", "OrderCity"}, {"Order Country", "OrderCountry"},
        {"Order Customer Id", "OrderCustomerID"}, {"order date (DateOrders)", "OrderDate"},
        {"Order Id", "OrderID"}, {"Order Item Cardprod Id", "OrderItemCardProdID"},
        {"Order Item Discount", "OrderItemDiscount"}, {"Order Item Discount Rate", "DiscountRate"},
        {"Order Item Id", "OrderItemID"}, {"Order Item Product Price", "UnitPrice"},
        {"Order Item Profit Ratio", "ProfitRatio"}, {"Order Item Quantity", "Quantity"},
        {"Order Item Total", "OrderItemTotal"}, {"Order Profit Per Order", "OrderProfitPerOrder"},
        {"Order Region", "OrderRegion"}, {"Order State", "OrderState"},
        {"Order Status", "OrderStatus"}, {"Order Zipcode", "OrderZipcode"},
        {"Product Card Id", "ProductID"}, {"Product Category Id", "ProductCategoryID"},
        {"Product Name", "ProductName"}, {"Product Price", "ProductPrice"},
        {"Product Status", "ProductStatus"}, {"shipping date (DateOrders)", "ShippingDate"},
        {"Shipping Mode", "ShippingMode"}
    }),

    // 6. Add surrogate date keys for relating to Dim_Date
    AddedOrderDateKey = Table.AddColumn(RenamedColumns, "OrderDateKey", each Date.ToText(DateTime.Date([OrderDate]), "yyyyMMdd"), type text),
    AddedShipDateKey = Table.AddColumn(AddedOrderDateKey, "ShippingDateKey", each Date.ToText(DateTime.Date([ShippingDate]), "yyyyMMdd"), type text),
    ChangedKeyTypes = Table.TransformColumnTypes(AddedShipDateKey, {{"OrderDateKey", Int64.Type}, {"ShippingDateKey", Int64.Type}})
in
    ChangedKeyTypes

// =====================================================================
// After this base query ("SupplyChain_Base"), create each star-schema
// table as a REFERENCE of this query (right-click → Reference), then
// on each reference: Choose Columns → keep only that table's columns →
// Remove Duplicates on the key column. This avoids re-reading the CSV
// 6 times and keeps everything driven by one clean source.
//
// Dim_Customer   <- Reference -> Choose Columns: CustomerID, CustomerCity, CustomerState, CustomerCountry, CustomerSegment, CustomerZipcode -> Remove Duplicates on CustomerID
// Dim_Product    <- Reference -> Choose Columns: ProductID, ProductName, ProductPrice, ProductStatus, ProductCategoryID, CategoryID, CategoryName -> Remove Duplicates on ProductID
// Dim_Department <- Reference -> Choose Columns: DepartmentID, DepartmentName -> Remove Duplicates on DepartmentID
// Dim_Order      <- Reference -> Choose Columns: OrderID, OrderStatus, ShippingMode, DeliveryStatus, Market, OrderRegion, OrderCountry, OrderState, OrderCity, OrderZipcode, PaymentType, DaysForShippingReal, DaysForShipmentScheduled, LateDeliveryRisk -> Remove Duplicates on OrderID
// Fact_OrderDetails <- Reference -> Choose Columns: OrderItemID, OrderID, CustomerID, ProductID, DepartmentID, OrderDateKey, ShippingDateKey, Quantity, UnitPrice, Sales, OrderItemDiscount, DiscountRate, OrderItemTotal, BenefitPerOrder, OrderProfitPerOrder, ProfitRatio, SalesPerCustomer
//
// Dim_Date: Home -> New Source -> Blank Query -> Advanced Editor -> paste the Dim_Date M script below
// =====================================================================
